package main

import "fmt"

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

func fibonacciSumToLimit(limit int) int {
	n, m := 1, 2
	sum := 0
	for m <= limit {
		if m%2 == 0 {
			sum += m
		}
		n, m = m, n+m
	}
	return sum
}

func solve() int {
	return fibonacciSumToLimit(4000000)
}

func main() {
	fmt.Printf("The sum of even-valued Fibonacci terms less than 4,000,000 is %d\n", solve())
}
